---
# tasks file for roles/app

    - name: Create a simple-api container
      docker_container:
        name: backend
        image: nathandoyen/tp-devops-epf-nathan:simple-api
        networks:
          - name: "app-network"
